#!/bin/zsh
function max {
  return $(($1 > $2 ? $1 : $2))
}

outdir=squares
mkdir $outdir

for i in *.(jpg|jpeg|png)
do
  echo "resizing $i..."
  dimensions=$(magick identify $i | grep -Eo '[0-9]+x[0-9]+' | head -n 1)
  x=$(echo $dimensions | cut -d'x' -f1)
  y=$(echo $dimensions | cut -d'x' -f2)
  max $x $y
  magick $i -resize $?x$? -background black -compose Copy \
  -gravity center -extent $?x$? -quality 90 $outdir/$i
done
echo "done"
