#!/bin/zsh
function max {
  return $(($1 > $2 ? $1 : $2))
}

outdir=squares
mkdir -p $outdir

for i in *.(jpg|jpeg|png)
do
  echo "Squaring $i..."
  # https://legacy.imagemagick.org/Usage/thumbnails/#square
  convert $IMAGE \
          \( +clone -rotate 90 +clone -mosaic +level-colors white \) \
          +swap -gravity center -composite $outdir/$i
done
echo "Done"
